### ISSUE TITLE
Encourage users to sign in using SSO options

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-authn#3]
![image](https://user-images.githubusercontent.com/13796098/156747578-7f961347-3455-4cb1-ad69-a5be603da8d5.png)

[Wireframes](https://www.figma.com/file/nj9XpgMFZutASCldiGbKXE/Learning-Platform?node-id=1802%3A1967)

**Comment by Salik-Rafiq** [comment]
Just need to await the approval of the PR for issue #2 and then I can rebase this from master and submit a further PR.
